### ISSUE TITLE
DECK OF CARD SIMULATION

### ISSUE THREAD

**Issue by 1-ARIjitS** [1-ARIjitS/CP#1]
simulate a deck of card using c++ and output all the card colors and values to a text file.
you have to stop the simulation when the random card generated is same as the top card generated when you simulate the deck of card.

**Comment by 1-ARIjitS** [comment]
also, attach the **output.txt** file with your work.
it will not be accepted without it.
it will be checked on different test cases such as 
1. having different outputs every time you run it.
2. never the same first/top card.

**Comment by Aliex-dev** [comment]
i want to do it i will attach al files as hacktoberfest starts , can it be in c?

**Comment by 1-ARIjitS** [comment]
yes you can do it in c but you have to port it to c++ eventually i am assigning you 
but after reviewing it fully i will merge it
